name: GitHub-Profile-Summary-Cards

on:
  create:
  push:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
      - uses: tuhin18003/profile-summary-card-example@release
        env:
          GITHUB_TOKEN: ${{ secrets.profile_summary_card_example }}
        with:
          USERNAME: ${{ github.repository_owner }}
